<?php

namespace Drupal\phpunit_test\Unit\Controller;


use Drupal\phpunit_test\Controller\ControllerBasic;
use Drupal\Tests\UnitTestCase;


/**
 * Class ControllerBasicTest
 *
 * @group phpunit_test
 */
class ControllerBasicTest extends UnitTestCase {
  protected $object;
  protected $response;
  protected function setUp(): void
  {
    $consultDate = $this->createTestMock('Drupal\phpunit_test\Services\ConsultDate', ['getCurrentDate']);

    $messenger = $this->createTestMock('Drupal\Core\Messenger\MessengerInterface');
    $this->object = new ControllerBasic($consultDate, $messenger);
    parent::setUp(); // TODO: Change the autogenerated stub
  }

  public function tearDown(): void
  {
    unset($this->object);
    unset($this->response);
    parent::tearDown(); // TODO: Change the autogenerated stub
  }

  public function createTestMock($mockClass, $methsMock = []) {
    return $this->getMockBuilder($mockClass)
      ->disableOriginalConstructor()
      ->setMethods($methsMock)
      ->getMock();
  }

  public function testView() {
    $this->setUp();
    $this->response = $this->object->view(2);
    $this->assertIsArray($this->response);
    $this->tearDown();
  }

  /*
   * Parametro uno
   */
  public function testViewUno() {
    $this->setUp();
    $this->response = $this->object->view(1);
    $this->assertIsArray($this->response);
    $this->tearDown();
  }


}
