<?php

namespace Drupal\phpunit_test_seed\Unit\Services;

use Drupal\phpunit_test_seed\Services\ConsultDate;
use Drupal\Tests\UnitTestCase;

/**
 * Provides unit tests for
 *
 * @coversDefaultClass \Drupal\phpunit_test_seed\Services\ConsultDate
 *
 * @group phpunit_test_seed
 */
class ConsultDateTest extends UnitTestCase {


  protected $object;
  protected $response;
  protected function setUp()
  {
    parent::setUp();
    $this->object = new ConsultDate();
  }

  protected function tearDown(): void
  {
    parent::tearDown(); // TODO: Change the autogenerated stub
    unset($this->object);
    unset($this->response);
  }

  public function testInitConsult() {
    $this->setUp();
    $this->response = $this->object->getCurrentDate('custom', 'Y-m-d H:i:s');
    $this->assertIsString($this->response);
    $this->tearDown();
  }
}
